### ISSUE TITLE
The ability to enter text..

### ISSUE THREAD

**Issue by epic6666** [unruhschuh/MrWriter#20] opened 2019-01-24 05:48 UTC
..would be greatly appreciated. I see a fork here has (apparently) already implemented it: https://github.com/AlexD97/MrWriter
Perhaps you can cannibalize the code from it? A decent method for text-entry is all this program needs to be a OneNote killer tbh.
Thanks for your work!

**Comment by unruhschuh** [comment] 2019-01-24 06:11
I'm currently working on adding images (jpg, png,...). Text is next, but I cannot make a promise as to when that'll happen.

Images btw are a prerequisite to text, since I'll render the text as an image and I want text to be rotatable/resizable.

**Comment by unruhschuh** [comment] 2019-01-25 09:10
Duplicate of #16

**Comment by unruhschuh** [comment] 2019-02-02 09:56
Text is here! Let me know what you think.

![screenshot 2019-02-02 at 10 40 35](https://user-images.githubusercontent.com/13489581/52162670-c2d3df00-26d7-11e9-812f-3437779c3143.png)

**Comment by unruhschuh** [comment] 2019-02-02 10:25
This is fun
![screenshot 2019-02-02 at 11 19 30](https://user-images.githubusercontent.com/13489581/52163058-fbc28280-26dc-11e9-8d77-9297498377fa.png)

**Closed as completed** 2019-02-02 17:03 UTC
Labels: duplicate, enhancement
